set(VCPKG_TARGET_ARCHITECTURE arm)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME Android)

if(NOT ENV{ANDROID_NATIVE_API_LEVEL})
	set(ENV{ANDROID_NATIVE_API_LEVEL} 23)
endif()
