set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME Android)

set(ANDROID_API_LEVEL 23)
set(ANDROID_SDK_ROOT "$ENV{ANDROID_SDK_ROOT}")
set(ANDROID_NDK_HOME "$ENV{ANDROID_NDK_HOME}")
set(toolchain_root "${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin")
set(ENV{PATH} "${toolchain_root}:/usr/local/bin:/usr/bin:/bin")

set(ENV{CC}      x86_64-linux-android${ANDROID_API_LEVEL}-clang)
set(ENV{CXX}     x86_64-linux-android${ANDROID_API_LEVEL}-clang++)
set(ENV{AR}      llvm-ar)
set(ENV{NM}      llvm-nm)
set(ENV{RANLIB}  llvm-ranlib)
set(ENV{READELF} llvm-readelf)
set(ENV{STRIP}   llvm-strip)
set(ENV{OBJDUMP}   llvm-objdump)
